openapi: 3.0.0
info:
  version: latest
  title: League Manager API
  description: This is the API for the League Manager

servers:
  - url: https://api.bthree.uk/leagues/v1
    description: Production server

tags:
  - name: players
    description: Operations about F1 seasons

paths:
  /players:
    get:
      tags:
        - players
      summary: Get all players
      operationId: getPlayers
      parameters:
        - $ref: '../../../../vendor/github.com/Jacobbrewer1/pagefilter/common/common.yaml#/components/parameters/limit_param'
        - $ref: '../../../../vendor/github.com/Jacobbrewer1/pagefilter/common/common.yaml#/components/parameters/last_value'
        - $ref: '../../../../vendor/github.com/Jacobbrewer1/pagefilter/common/common.yaml#/components/parameters/last_id'
        - $ref: '../../../../vendor/github.com/Jacobbrewer1/pagefilter/common/common.yaml#/components/parameters/sort_by'
        - $ref: '../../../../vendor/github.com/Jacobbrewer1/pagefilter/common/common.yaml#/components/parameters/sort_direction'
        - $ref: '#/components/parameters/query_name'
        - $ref: '#/components/parameters/query_year'
      responses:
        '200':
          description: A list of players
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/players_response'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../common/common.yaml#/components/schemas/error_message'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '../common/common.yaml#/components/schemas/error_message'
    post:
      tags:
        - players
      summary: Create a player
      operationId: createPlayer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/player'
      responses:
        '201':
          description: Player created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/player'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../common/common.yaml#/components/schemas/error_message'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '../common/common.yaml#/components/schemas/error_message'

  /players/{id}:
    get:
      tags:
        - players
      summary: Get a player by ID
      operationId: getPlayerByID
      parameters:
        - name: id
          in: path
          description: The ID of the player
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A player
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/player'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../common/common.yaml#/components/schemas/error_message'
        '404':
          description: Player not found
          content:
            application/json:
              schema:
                $ref: '../common/common.yaml#/components/schemas/error_message'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '../common/common.yaml#/components/schemas/error_message'
    patch:
      tags:
        - players
      summary: Update a player
      operationId: updatePlayer
      parameters:
        - name: id
          in: path
          description: The ID of the player
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/player'
      responses:
        '200':
          description: Player updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/player'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../common/common.yaml#/components/schemas/error_message'
        '404':
          description: Player not found
          content:
            application/json:
              schema:
                $ref: '../common/common.yaml#/components/schemas/error_message'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '../common/common.yaml#/components/schemas/error_message'

components:
  parameters:
    query_year:
      name: year
      in: query
      description: The year of the season
      required: false
      schema:
        type: integer
        format: int64
    query_year_min:
      name: year_min
      in: query
      description: The minimum year of the season
      required: false
      schema:
        type: integer
        format: int64
    query_year_max:
      name: year_max
      in: query
      description: The maximum year of the season
      required: false
      schema:
        type: integer
        format: int64
    query_name:
      name: name
      in: query
      description: The name to filter by
      required: false
      schema:
        type: string

  schemas:
    players_response:
      type: object
      required:
        - players
        - total
      properties:
        players:
          type: array
          items:
            $ref: '#/components/schemas/player'
        total:
          type: integer
          format: int64

    player:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
        date_of_birth:
          type: string
          format: date

    team:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        contact_email:
          type: string
          format: email
        contact_phone:
          type: string
