// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	externalRef0 "github.com/Jacobbrewer1/pagefilter/common"
)

// Player defines the model for player.
type Player struct {
	Id   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// PlayersResponse defines the model for players_response.
type PlayersResponse struct {
	Players []Player `json:"players"`
	Total   int64    `json:"total"`
}

// QueryName defines the model for query_name.
type QueryName = string

// QueryYear defines the model for query_year.
type QueryYear = int64

// GetPlayersParams defines parameters for GetPlayers.
type GetPlayersParams struct {
	// Limit Report type
	Limit *externalRef0.LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// LastVal Pagination details, last value of the sort column on the previous page.
	LastVal *externalRef0.LastValue `form:"last_val,omitempty" json:"last_val,omitempty"`

	// LastId Pagination details, last value of the id column on the previous page.
	LastId *externalRef0.LastId `form:"last_id,omitempty" json:"last_id,omitempty"`

	// SortBy Pagination details, sort column, if empty uses the id column.
	SortBy *externalRef0.SortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Pagination details, sorting order.
	SortDir *GetPlayersParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`

	// Name The name to filter by
	Name *QueryName `form:"name,omitempty" json:"name,omitempty"`

	// Year The year of the season
	Year *QueryYear `form:"year,omitempty" json:"year,omitempty"`
}

// GetPlayersParamsSortDir defines parameters for GetPlayers.
type GetPlayersParamsSortDir string
