// Package models contains the database interaction model code
//
// GENERATED BY GOSCHEMA. DO NOT EDIT.
package models

import (
	"errors"
	"fmt"
	"time"

	"github.com/jacobbrewer1/goschema/pkg/usql"
	"github.com/jacobbrewer1/patcher"
	"github.com/jacobbrewer1/patcher/inserter"
	"github.com/prometheus/client_golang/prometheus"
)

// Game represents a row from 'game'.
type Game struct {
	Id             int       `db:"id,autoinc,pk"`
	SeasonId       int       `db:"season_id"`
	HomePartnersId int       `db:"home_partners_id"`
	AwayPartnersId int       `db:"away_partners_id"`
	MatchDate      time.Time `db:"match_date"`
	WinningTeam    usql.Enum `db:"winning_team"`
}

// Insert inserts the Game to the database.
func (m *Game) Insert(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_Game"))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO game (" +
		"`season_id`, `home_partners_id`, `away_partners_id`, `match_date`, `winning_team`" +
		") VALUES (" +
		"?, ?, ?, ?, ?" +
		")"

	DBLog(sqlstr, m.SeasonId, m.HomePartnersId, m.AwayPartnersId, m.MatchDate, m.WinningTeam)
	res, err := db.Exec(sqlstr, m.SeasonId, m.HomePartnersId, m.AwayPartnersId, m.MatchDate, m.WinningTeam)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

func InsertManyGames(db DB, ms ...*Game) error {
	if len(ms) == 0 {
		return nil
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_many_Game"))
	defer t.ObserveDuration()

	vals := make([]any, 0, len(ms))
	for _, m := range ms {
		// Dereference the pointer to get the struct value.
		vals = append(vals, []any{*m})
	}

	sqlstr, args, err := inserter.NewBatch(vals, inserter.WithTable("game")).GenerateSQL()
	if err != nil {
		return fmt.Errorf("failed to create batch insert: %w", err)
	}

	DBLog(sqlstr, args...)
	res, err := db.Exec(sqlstr, args...)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	for i, m := range ms {
		m.Id = int(id + int64(i))
	}

	return nil
}

// IsPrimaryKeySet returns true if all primary key fields are set to none zero values
func (m *Game) IsPrimaryKeySet() bool {
	return IsKeySet(m.Id)
}

// Update updates the Game in the database.
func (m *Game) Update(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("update_Game"))
	defer t.ObserveDuration()

	const sqlstr = "UPDATE game " +
		"SET `season_id` = ?, `home_partners_id` = ?, `away_partners_id` = ?, `match_date` = ?, `winning_team` = ? " +
		"WHERE `id` = ?"

	DBLog(sqlstr, m.SeasonId, m.HomePartnersId, m.AwayPartnersId, m.MatchDate, m.WinningTeam, m.Id)
	res, err := db.Exec(sqlstr, m.SeasonId, m.HomePartnersId, m.AwayPartnersId, m.MatchDate, m.WinningTeam, m.Id)
	if err != nil {
		return err
	}

	// Requires clientFoundRows=true
	if i, err := res.RowsAffected(); err != nil {
		return err
	} else if i <= 0 {
		return ErrNoAffectedRows
	}

	return nil
}

func (m *Game) Patch(db DB, newT *Game) error {
	if newT == nil {
		return errors.New("new game is nil")
	}

	res, err := patcher.NewDiffSQLPatch(m, newT, patcher.WithTable("game"))
	if err != nil {
		return fmt.Errorf("new diff sql patch: %w", err)
	}

	sqlstr, args, err := res.GenerateSQL()
	if err != nil {
		switch {
		case errors.Is(err, patcher.ErrNoChanges):
			return nil
		default:
			return fmt.Errorf("failed to create patch: %w", err)
		}
	}

	DBLog(sqlstr, args...)
	_, err = db.Exec(sqlstr, args...)
	if err != nil {
		return fmt.Errorf("failed to execute patch: %w", err)
	}

	return nil
}

// InsertWithUpdate inserts the Game to the database, and tries to update
// on unique constraint violations.
func (m *Game) InsertWithUpdate(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_update_Game"))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO game (" +
		"`season_id`, `home_partners_id`, `away_partners_id`, `match_date`, `winning_team`" +
		") VALUES (" +
		"?, ?, ?, ?, ?" +
		") ON DUPLICATE KEY UPDATE " +
		"`season_id` = VALUES(`season_id`), `home_partners_id` = VALUES(`home_partners_id`), `away_partners_id` = VALUES(`away_partners_id`), `match_date` = VALUES(`match_date`), `winning_team` = VALUES(`winning_team`)"

	DBLog(sqlstr, m.SeasonId, m.HomePartnersId, m.AwayPartnersId, m.MatchDate, m.WinningTeam)
	res, err := db.Exec(sqlstr, m.SeasonId, m.HomePartnersId, m.AwayPartnersId, m.MatchDate, m.WinningTeam)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

// Save saves the Game to the database.
func (m *Game) Save(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.Insert(db)
}

// SaveOrUpdate saves the Game to the database, but tries to update
// on unique constraint violations.
func (m *Game) SaveOrUpdate(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.InsertWithUpdate(db)
}

// Delete deletes the Game from the database.
func (m *Game) Delete(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("delete_Game"))
	defer t.ObserveDuration()

	const sqlstr = "DELETE FROM game WHERE `id` = ?"

	DBLog(sqlstr, m.Id)
	_, err := db.Exec(sqlstr, m.Id)

	return err
}

// GameById retrieves a row from 'game' as a Game.
//
// Generated from primary key.
func GameById(db DB, id int) (*Game, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_Game"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `season_id`, `home_partners_id`, `away_partners_id`, `match_date`, `winning_team` " +
		"FROM game " +
		"WHERE `id` = ?"

	DBLog(sqlstr, id)
	var m Game
	if err := db.Get(&m, sqlstr, id); err != nil {
		return nil, err
	}

	return &m, nil
}

// GetSeasonIdSeason Gets an instance of Season
//
// Generated from constraint game_season_id_fk
func (m *Game) GetSeasonIdSeason(db DB) (*Season, error) {
	return SeasonById(db, m.SeasonId)
}

// GetHomePartnersIdPartnership Gets an instance of Partnership
//
// Generated from constraint game_partnership_id_fk
func (m *Game) GetHomePartnersIdPartnership(db DB) (*Partnership, error) {
	return PartnershipById(db, m.HomePartnersId)
}

// GetAwayPartnersIdPartnership Gets an instance of Partnership
//
// Generated from constraint game_partnership_id_fk2
func (m *Game) GetAwayPartnersIdPartnership(db DB) (*Partnership, error) {
	return PartnershipById(db, m.AwayPartnersId)
}

// Valid values for the 'WinningTeam' enum column
var (
	GameWinningTeamHome = "HOME"
	GameWinningTeamAway = "AWAY"
)
