// Package models contains the database interaction model code
//
// GENERATED BY GOSCHEMA. DO NOT EDIT.
package models

import (
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

// Players represents a row from 'players'.
type Players struct {
	Id        int       `db:"id,autoinc,pk"`
	FirstName string    `db:"first_name"`
	LastName  string    `db:"last_name"`
	Email     string    `db:"email"`
	Dob       time.Time `db:"dob"`
	UpdatedAt time.Time `db:"updated_at"`
}

// PlayersColumns is the sorted column names for the type Players
var PlayersColumns = []string{"Dob", "Email", "FirstName", "Id", "LastName", "UpdatedAt"}

// Insert inserts the Players to the database.
func (m *Players) Insert(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_Players"))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO players (" +
		"`first_name`, `last_name`, `email`, `dob`, `updated_at`" +
		") VALUES (" +
		"?, ?, ?, ?, ?" +
		")"

	DBLog(sqlstr, m.FirstName, m.LastName, m.Email, m.Dob, m.UpdatedAt)
	res, err := db.Exec(sqlstr, m.FirstName, m.LastName, m.Email, m.Dob, m.UpdatedAt)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

func InsertManyPlayerss(db DB, ms ...*Players) error {
	if len(ms) == 0 {
		return nil
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_many_Players"))
	defer t.ObserveDuration()

	var sqlstr = "INSERT INTO players (" +
		"`first_name`,`last_name`,`email`,`dob`,`updated_at`" +
		") VALUES"

	var args []interface{}
	for _, m := range ms {
		sqlstr += " (" +
			"?,?,?,?,?" +
			"),"
		args = append(args, m.FirstName, m.LastName, m.Email, m.Dob, m.UpdatedAt)
	}

	DBLog(sqlstr, args...)
	res, err := db.Exec(sqlstr, args...)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	for i, m := range ms {
		m.Id = int(id + int64(i))
	}

	return nil
}

// IsPrimaryKeySet returns true if all primary key fields are set to none zero values
func (m *Players) IsPrimaryKeySet() bool {
	return IsKeySet(m.Id)
}

// Update updates the Players in the database.
func (m *Players) Update(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("update_Players"))
	defer t.ObserveDuration()

	const sqlstr = "UPDATE players " +
		"SET `first_name` = ?, `last_name` = ?, `email` = ?, `dob` = ?, `updated_at` = ? " +
		"WHERE `id` = ?"

	DBLog(sqlstr, m.FirstName, m.LastName, m.Email, m.Dob, m.UpdatedAt, m.Id)
	res, err := db.Exec(sqlstr, m.FirstName, m.LastName, m.Email, m.Dob, m.UpdatedAt, m.Id)
	if err != nil {
		return err
	}

	// Requires clientFoundRows=true
	if i, err := res.RowsAffected(); err != nil {
		return err
	} else if i <= 0 {
		return ErrNoAffectedRows
	}

	return nil
}

// InsertWithUpdate inserts the Players to the database, and tries to update
// on unique constraint violations.
func (m *Players) InsertWithUpdate(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_update_Players"))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO players (" +
		"`first_name`, `last_name`, `email`, `dob`, `updated_at`" +
		") VALUES (" +
		"?, ?, ?, ?, ?" +
		") ON DUPLICATE KEY UPDATE " +
		"`first_name` = VALUES(`first_name`), `last_name` = VALUES(`last_name`), `email` = VALUES(`email`), `dob` = VALUES(`dob`), `updated_at` = VALUES(`updated_at`)"

	DBLog(sqlstr, m.FirstName, m.LastName, m.Email, m.Dob, m.UpdatedAt)
	res, err := db.Exec(sqlstr, m.FirstName, m.LastName, m.Email, m.Dob, m.UpdatedAt)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

// Save saves the Players to the database.
func (m *Players) Save(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.Insert(db)
}

// SaveOrUpdate saves the Players to the database, but tries to update
// on unique constraint violations.
func (m *Players) SaveOrUpdate(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.InsertWithUpdate(db)
}

// Delete deletes the Players from the database.
func (m *Players) Delete(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("delete_Players"))
	defer t.ObserveDuration()

	const sqlstr = "DELETE FROM players WHERE `id` = ?"

	DBLog(sqlstr, m.Id)
	_, err := db.Exec(sqlstr, m.Id)

	return err
}

// PlayersById retrieves a row from 'players' as a Players.
//
// Generated from primary key.
func PlayersById(db DB, id int) (*Players, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_Players"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `first_name`, `last_name`, `email`, `dob`, `updated_at` " +
		"FROM players " +
		"WHERE `id` = ?"

	DBLog(sqlstr, id)
	var m Players
	if err := db.Get(&m, sqlstr, id); err != nil {
		return nil, err
	}

	return &m, nil
}

// PlayersByEmail retrieves a row from 'players' as a *Players.
//
// Generated from index 'players_email_uindex' of type 'unique'.
func PlayersByEmail(db DB, email string) (*Players, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_Players"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `first_name`, `last_name`, `email`, `dob`, `updated_at` " +
		"FROM players " +
		"WHERE `email` = ?"

	DBLog(sqlstr, email)
	var m Players
	if err := db.Get(&m, sqlstr, email); err != nil {
		return nil, err
	}

	return &m, nil
}
