// Package models contains the database interaction model code
//
// GENERATED BY GOSCHEMA. DO NOT EDIT.
package models

import (
	"fmt"

	"github.com/Jacobbrewer1/patcher/inserter"
	"github.com/prometheus/client_golang/prometheus"
)

// Season represents a row from 'season'.
type Season struct {
	Id   int    `db:"id,autoinc,pk"`
	Name string `db:"name"`
}

// Insert inserts the Season to the database.
func (m *Season) Insert(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_Season"))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO season (" +
		"`name`" +
		") VALUES (" +
		"?" +
		")"

	DBLog(sqlstr, m.Name)
	res, err := db.Exec(sqlstr, m.Name)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

func InsertManySeasons(db DB, ms ...*Season) error {
	if len(ms) == 0 {
		return nil
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_many_Season"))
	defer t.ObserveDuration()

	vals := make([]any, 0, len(ms))
	for _, m := range ms {
		// Dereference the pointer to get the struct value.
		vals = append(vals, []any{*m})
	}

	sqlstr, args, err := inserter.NewBatch(vals, inserter.WithTable("season")).GenerateSQL()
	if err != nil {
		return fmt.Errorf("failed to create batch insert: %w", err)
	}

	DBLog(sqlstr, args...)
	res, err := db.Exec(sqlstr, args...)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	for i, m := range ms {
		m.Id = int(id + int64(i))
	}

	return nil
}

// IsPrimaryKeySet returns true if all primary key fields are set to none zero values
func (m *Season) IsPrimaryKeySet() bool {
	return IsKeySet(m.Id)
}

// Update updates the Season in the database.
func (m *Season) Update(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("update_Season"))
	defer t.ObserveDuration()

	const sqlstr = "UPDATE season " +
		"SET `name` = ? " +
		"WHERE `id` = ?"

	DBLog(sqlstr, m.Name, m.Id)
	res, err := db.Exec(sqlstr, m.Name, m.Id)
	if err != nil {
		return err
	}

	// Requires clientFoundRows=true
	if i, err := res.RowsAffected(); err != nil {
		return err
	} else if i <= 0 {
		return ErrNoAffectedRows
	}

	return nil
}

// InsertWithUpdate inserts the Season to the database, and tries to update
// on unique constraint violations.
func (m *Season) InsertWithUpdate(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_update_Season"))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO season (" +
		"`name`" +
		") VALUES (" +
		"?" +
		") ON DUPLICATE KEY UPDATE " +
		"`name` = VALUES(`name`)"

	DBLog(sqlstr, m.Name)
	res, err := db.Exec(sqlstr, m.Name)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

// Save saves the Season to the database.
func (m *Season) Save(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.Insert(db)
}

// SaveOrUpdate saves the Season to the database, but tries to update
// on unique constraint violations.
func (m *Season) SaveOrUpdate(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.InsertWithUpdate(db)
}

// Delete deletes the Season from the database.
func (m *Season) Delete(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("delete_Season"))
	defer t.ObserveDuration()

	const sqlstr = "DELETE FROM season WHERE `id` = ?"

	DBLog(sqlstr, m.Id)
	_, err := db.Exec(sqlstr, m.Id)

	return err
}

// SeasonById retrieves a row from 'season' as a Season.
//
// Generated from primary key.
func SeasonById(db DB, id int) (*Season, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_Season"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `name` " +
		"FROM season " +
		"WHERE `id` = ?"

	DBLog(sqlstr, id)
	var m Season
	if err := db.Get(&m, sqlstr, id); err != nil {
		return nil, err
	}

	return &m, nil
}

// SeasonByName retrieves a row from 'season' as a *Season.
//
// Generated from index 'season_name_uindex' of type 'unique'.
func SeasonByName(db DB, name string) (*Season, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_Season"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `name` " +
		"FROM season " +
		"WHERE `name` = ?"

	DBLog(sqlstr, name)
	var m Season
	if err := db.Get(&m, sqlstr, name); err != nil {
		return nil, err
	}

	return &m, nil
}
